spring:
  application.name: product
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_database_username
    password: your_database_password
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090